### ISSUE TITLE
Invalid syntax on Python 3.6 and lolviz 1.2.1

### ISSUE THREAD

**Issue by srid** [parrt/lolviz#12]
Contd. from https://github.com/parrt/lolviz/issues/11#issuecomment-326474125

```
Traceback (most recent call last):

  File "/Users/srid/code/ipython/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-ae470ca34f62>", line 1, in <module>
    from lolviz import *

  File "/Users/srid/code/ipython/lib/python3.6/site-packages/lolviz.py", line 442
    print "hashcode =", hashcode(key)
                     ^
SyntaxError: invalid syntax

```

**Comment by parrt** [comment]
@srid try now! :) v 1.2.2
